#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

if ! echo "$commit_msg" | grep -Eq "^(fix|feat): .+"; then
  echo "❌ Invalid commit message format."
  echo "✅ Allowed: 'fix: some message' or 'feat: some message'"
  exit 1
fi
